### ISSUE TITLE
Can't set settings for multiple devices

### ISSUE THREAD

**Issue by jdayellow** [gblazex/smoothscroll#166] opened 2018-05-06 06:24 UTC
I would like to have different settings for my laptop and desktop PC. The laptop has much more sensitive scrolling so I reduced the settings, but the settings synced over to my desktop PC and my desktop scrolls much slower now.

**Comment by gblazex** [comment] 2019-10-22 13:26
duplicate of #65

**Closed by gblazex** 2019-10-22 13:26 UTC
